VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "CUnit"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Private m_Conn As ADODB.Connection

Public AddEditMode As SHOW_MODE_TYPE
Public QueryFlag As Long
Public OrderBy As Long
Public OrderType As Long
Public Flag As String
' End of generic data member

Public UNIT_ID As Long
Public UNIT_NO As String
Public UNIT_NAME As String
Public PERIOD_TYPE As Long
 
Public KEY_ID As Long
Public KEY_LOOKUP As String

Private Sub Class_Initialize()
   Set m_Conn = glbDatabaseMngr.DBConnection
End Sub

'In this class we will not handle any error or any transaction
Public Function QueryData(Rs As ADODB.Recordset, itemcount As Long)
Dim SQL1 As String
Dim SQL2 As String
Dim SelectStr1 As String
Dim SelectStr2 As String
Dim FromStr As String
Dim WhereStr As String
Dim OrderByStr As String
Dim OrderTypeStr As String

   SelectStr1 = "SELECT UG.*  "
   SelectStr2 = "SELECT COUNT(*)  "
   
   FromStr = "FROM UNIT UG "
   
   WhereStr = ""
   If UNIT_ID > 0 Then
      If Len(WhereStr) <= 0 Then
         WhereStr = "WHERE (UNIT_ID = " & UNIT_ID & ") "
      Else
         WhereStr = WhereStr & "AND (UNIT_ID = " & UNIT_ID & ") "
      End If
   End If
   
   OrderByStr = ""
   OrderTypeStr = ""

   If OrderBy = 1 Then
      OrderByStr = "ORDER BY UNIT_ID "
   ElseIf OrderBy = 2 Then
      OrderByStr = "ORDER BY UNIT_NAME "
   Else
      OrderByStr = "ORDER BY UNIT_ID "
   End If
   
   If OrderType = 1 Then
      OrderTypeStr = "ASC "
   ElseIf OrderType = 2 Then
      OrderTypeStr = "DESC "
   Else
      OrderTypeStr = "DESC "
   End If
   
   SQL1 = SelectStr1 & FromStr & WhereStr & OrderByStr & OrderTypeStr
   SQL2 = SelectStr2 & FromStr & WhereStr
   
   Call glbDatabaseMngr.GetRs(SQL1, SQL2, True, itemcount, Rs, glbErrorLog)
End Function

Public Function PopulateFromRS(Ind As Long, Rs As ADODB.Recordset)
   UNIT_ID = NVLI(Rs("UNIT_ID"), -1)
   UNIT_NAME = NVLS(Rs("UNIT_NAME"), "")
   UNIT_NO = NVLS(Rs("UNIT_NO"), "")
   PERIOD_TYPE = NVLI(Rs("PERIOD_TYPE"), -1)
End Function

Public Function AddEditData(Optional AutoGenerateFlag As Boolean = True)
Dim ServerDateTime As String
Dim SQL1 As String
Dim ID As Long

   Call glbDatabaseMngr.GetServerDateTime(ServerDateTime, glbErrorLog)

   If AddEditMode = SHOW_ADD Then
      If AutoGenerateFlag Then
         Call glbDatabaseMngr.GetSeqID("UNIT_SEQ", ID, glbErrorLog)
      Else
         ID = UNIT_ID
      End If

      SQL1 = "INSERT INTO UNIT " & _
                     "( " & _
                     "   UNIT_ID, " & _
                     "   UNIT_NAME, " & _
                     "   UNIT_NO, " & _
                     "   PERIOD_TYPE, " & _
                     "   CREATE_DATE, " & _
                    "    CREATE_BY, " & _
                    "    MODIFY_DATE, " & _
                    "    MODIFY_BY " & _
                     ") " & _
                     "VALUES " & _
                     "( " & _
                         ID & "," & _
                         "'" & ChangeQuote(Trim(UNIT_NAME)) & "'," & _
                         "'" & ChangeQuote(Trim(UNIT_NO)) & "'," & _
                         PERIOD_TYPE & "," & _
                         "'" & ServerDateTime & "'," & _
                         glbUser.USER_ID & "," & _
                         "'" & ServerDateTime & "'," & _
                         glbUser.USER_ID & _
                     ") "
         UNIT_ID = ID
   Else 'Show edit
      SQL1 = "UPDATE UNIT SET " & _
                     "   UNIT_NO = '" & ChangeQuote(Trim(UNIT_NO)) & "', " & _
                     "   UNIT_NAME = '" & ChangeQuote(Trim(UNIT_NAME)) & "', " & _
                     "    PERIOD_TYPE = " & PERIOD_TYPE & ",  " & _
                    "    MODIFY_DATE = '" & ServerDateTime & "', " & _
                    "    MODIFY_BY = " & glbUser.USER_ID & " " & _
                     "WHERE UNIT_ID = " & UNIT_ID
   End If
   
   If (AddEditMode = SHOW_ADD) Or (AddEditMode = SHOW_EDIT) Then
      m_Conn.Execute (SQL1)
   End If
End Function

Public Function DeleteData()
Dim SQL1 As String
      SQL1 = "DELETE FROM UNIT WHERE UNIT_ID = " & UNIT_ID
      m_Conn.Execute (SQL1)
End Function


