VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "CSumInventoryAccount"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Public PART_NO As String
Public SUM_INV_ACCOUNT As Double
Public SUM_INV_PHYSICAL As Double
Public AVR_UNIT_ACCOUNT As Double
Public AVR_UNIT_PHYSICAL As Double



      

