VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "CTempData"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Public ID As String
Public NAME As String
Public BALANCE_AMOUNT As String
Public BALANCE_AVR As String
Public BALANCE_VALUE As String
Public TX_AMOUNT As String
Public TX_AVR As String
Public TX_VALUE As String
Public USE_AMOUNT As String
Public USE_AVR As String
Public USE_VALUE As String
Public LEFT_AMOUNT As String
Public LEFT_AVR As String
Public LEFT_VALUE As String
Public DIFF_AMOUNT As String
Public DIFF_AVR As String
Public DIFF_VALUE As String
