
CREATE TABLE AGREEMENT
(
   AGREEMENT_ID          ID_TYPE NOT NULL,
   SOC_FEATURE_ID        ID_TYPE,
   SUBSCRIBER_ID         ID_TYPE NOT NULL,
   EFFECTIVE_DATE        DATE_TYPE,
   EXPIRE_DATE           DATE_TYPE,
   EXCLUDE_FLAG          FLAG_TYPE,
   ISSUE_DATE            DATE_TYPE,
   SOC_ID                ID_TYPE,
   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
