CREATE TABLE BILLING_ADJUST
(
   BILLING_ADJUST_ID     ID_TYPE NOT NULL,
   BILLING_DOC_ID        ID_TYPE NOT NULL,
   INVENTORY_DOC_ID      ID_TYPE NOT NULL,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
