
CREATE TABLE CUSTOMER_TYPE
(
   CSTTYPE_ID         ID_TYPE NOT NULL,
   CSTTYPE_NO         CODE_TYPE NOT NULL,
   CSTTYPE_NAME       CODE_TYPE NOT NULL,
   CREATE_DATE        DATE_TYPE NOT NULL,
   CREATE_BY          ID_TYPE NOT NULL,
   MODIFY_DATE        DATE_TYPE NOT NULL,
   MODIFY_BY          ID_TYPE NOT NULL
);
