
CREATE TABLE CUSTOMER_ADDRESS
(
   CUSTOMER_ADDRESS_ID   ID_TYPE NOT NULL,
   CUSTOMER_ID           ID_TYPE NOT NULL,
   ADDRESS_ID            ID_TYPE NOT NULL,
   ADDRESS_TYPE          ID_TYPE,
   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
