
CREATE TABLE CUSTOMER
(
   CUSTOMER_ID          ID_TYPE NOT NULL,
   CUSTOMER_CODE        CODE_TYPE,
   CUSTOMER_GRADE       ID_TYPE,
   CUSTOMER_TYPE        ID_TYPE,
   CREDIT               LEN_TYPE,
   TAX_ID               TAXID_TYPE,
   BIRTH_DATE           DATE_TYPE,
   EMAIL                EMAIL_TYPE,
   WEBSITE              WEB_TYPE,
   CUSTOMER_PASSWORD    PASSWORD_TYPE,
   BUSINESS_TYPE        ID_TYPE,
   BUSINESS_DESC        DESC_TYPE,
   RESPONSE_BY          ID_TYPE,
   NORMAL_DISCOUNT      MONEY_TYPE,

   CREATE_DATE          DATE_TYPE NOT NULL,
   CREATE_BY            ID_TYPE NOT NULL,
   MODIFY_DATE          DATE_TYPE NOT NULL,
   MODIFY_BY            ID_TYPE NOT NULL
);
