
CREATE TABLE EMPLOYEE_NAME
(
   EMPLOYEE_NAME_ID      ID_TYPE NOT NULL,
   EMP_ID                ID_TYPE NOT NULL,
   NAME_ID               ID_TYPE NOT NULL,
   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
