
CREATE TABLE EMP_POSITION
(
   POSITION_ID           ID_TYPE NOT NULL,
   PPOSITION_ID          ID_TYPE,
   POSITION_NAME         CODE_TYPE NOT NULL,
   POSITION_DESC         DESC_TYPE,
   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
