
CREATE TABLE EMPLOYEE
(
   EMP_ID                ID_TYPE NOT NULL,
   EMP_CODE              CODE_TYPE NOT NULL,
   SEX_ID                ID_TYPE,
   WEIGHT                WEIGHT_TYPE,
   HEIGHT                HEIGHT_TYPE,
   RACE                  CODE_TYPE,
   NATIONALITY           CODE_TYPE,
   RELIGIOUS_ID          ID_TYPE,
   MARITAL_ID            ID_TYPE,
   MILITALY_ID           ID_TYPE,
   BIRTH_DATE            DATE_TYPE,
   ENTRY_DATE            DATE_TYPE,
   DISCEASE              DESC_TYPE,
   MOBILE_PHONE          PHONE_TYPE,
   EMAIL_ADDRESS         EMAIL_TYPE,
   RESIGN_DATE           DATE_TYPE,
   CREMATION_DATE        DATE_TYPE,
   DUE_DATE              DATE_TYPE,
   APPEND_DATE           DATE_TYPE,
   ALLOWANCE_DATE        DATE_TYPE,
   PASS_DATE             DATE_TYPE,
   PASS_STATUS           FLAG_TYPE,
   WORK_STATUS_ID        ID_TYPE,
   BLOOD_GROUP           ID_TYPE,
   RESIGN_REASON         ID_TYPE,
   CURRENT_POSITION      ID_TYPE,
   CURRENT_SECTION       ID_TYPE,
   CURRENT_ORGANIZE      ID_TYPE,
   CURRENT_SALARY        MONEY_TYPE,
   CREDIT_AMOUNT         MONEY_TYPE,
   BANK_BRANCH           NAME_TYPE,
   BANK_ACCOUNT          NAME_TYPE,
   BANK_ID               ID_TYPE,
   EXTERNAL_FLAG         FLAG_TYPE,
   ASSURE_AMOUNT         MONEY_TYPE,
   OT_RATE               MONEY_TYPE,
   CARD_NO               CODE_TYPE,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
