
CREATE TABLE ENTERPRISE_ADDRESS
(
   ENTERPRISE_ADDRESS_ID   ID_TYPE NOT NULL,
   ENTERPRISE_ID           ID_TYPE NOT NULL,
   ADDRESS_ID              ID_TYPE NOT NULL,
   CREATE_DATE             DATE_TYPE NOT NULL,
   CREATE_BY               ID_TYPE NOT NULL,
   MODIFY_DATE             DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
