
CREATE TABLE ENTERPRISE_PERSON
(
   ENTERPRISE_PERSON_ID  ID_TYPE NOT NULL,
   ENTERPRISE_ID         ID_TYPE NOT NULL,
   NAME_ID               ID_TYPE NOT NULL,
   MASTER_FLAG           FLAG_TYPE,
   ADDRESS_ID            ID_TYPE,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
