CREATE TABLE EXPORT_ITEM
(
   EXPORT_ITEM_ID        ID_TYPE NOT NULL,
   INVENTORY_DOC_ID      ID_TYPE,
   PART_ITEM_ID          ID_TYPE NOT NULL,
   LOCATION_ID           ID_TYPE NOT NULL,
   HOUSE_ID              ID_TYPE,
   PIG_ID                ID_TYPE,
   PIG_IN_HOUSE          MONEY_TYPE,
   EXPORT_AMOUNT         AMOUNT_TYPE,
   EXPORT_AVG_PRICE      MONEY_TYPE,
   EXPORT_LAST_PRICE     MONEY_TYPE,
   PREVIOUS_AMOUNT       MONEY_TYPE,
   CURRENT_AMOUNT        MONEY_TYPE,
   TRANSACTION_SEQ       ID_TYPE NOT NULL,
   GUI_ID                ID_TYPE,
   CALCULATE_FLAG        FLAG_TYPE,
   PIG_STATUS            ID_TYPE,
   TOTAL_WEIGHT          MONEY_TYPE,
   LINK_ID               ID_TYPE,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
