
CREATE TABLE GROUP_RIGHT
(
   GROUP_RIGHT_ID       ID_TYPE NOT NULL,
   GROUP_ID             ID_TYPE NOT NULL,
   RIGHT_ID             ID_TYPE NOT NULL,
   RIGHT_STATUS         FLAG_TYPE NOT NULL,

   CREATE_DATE          DATE_TYPE NOT NULL,
   CREATE_BY            ID_TYPE NOT NULL,
   MODIFY_DATE          DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
