CREATE TABLE HGROUP_ITEM
(
   HGROUP_ITEM_ID        ID_TYPE NOT NULL,
   HOUSE_GROUP_ID        ID_TYPE NOT NULL,
   LOCATION_ID           ID_TYPE NOT NULL,
   SELECT_FLAG           FLAG_TYPE,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
