
CREATE TABLE HOUSE
(
   HOUSE_ID              ID_TYPE NOT NULL,
   HOUSE_NO              CODE_TYPE NOT NULL UNIQUE,
   HOUSE_NAME            CODE_TYPE NOT NULL UNIQUE,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
