CREATE TABLE HGROUP_ITEM
(
   HOUSE_GROUP_ID        ID_TYPE NOT NULL,
   HOUSE_GROUP_NO        CODE_TYPE,
   HOUSE_GROUP_NAME      NAME_TYPE,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
