CREATE TABLE IMPORT_ITEM
(
   IMPORT_ITEM_ID        ID_TYPE NOT NULL,
   INVENTORY_DOC_ID      ID_TYPE,
   PART_ITEM_ID          ID_TYPE NOT NULL,
   LOCATION_ID           ID_TYPE NOT NULL,
   ACTUAL_UNIT_PRICE     MONEY_TYPE,
   INCLUDE_UNIT_PRICE    MONEY_TYPE,
   PREVIOUS_PRICE        MONEY_TYPE,
   PREVIOUS_AMOUNT       MONEY_TYPE,
   NEW_PRICE             MONEY_TYPE,
   IMPORT_AMOUNT         MONEY_TYPE,
   CURRENT_AMOUNT        MONEY_TYPE,
   TRANSACTION_SEQ       ID_TYPE NOT NULL,
   GUI_ID                ID_TYPE,
   CALCULATE_FLAG        FLAG_TYPE,
   FATHER_NO             CODE_TYPE,
   MOTHER_NO             CODE_TYPE,
   TOTAL_WEIGHT          MONEY_TYPE,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
