
CREATE TABLE LOCATION
(
   LOCATION_ID           ID_TYPE NOT NULL,
   LOCATION_NO           CODE_TYPE NOT NULL,
   LOCATION_NAME         CODE_TYPE NOT NULL,
   LOCATION_TYPE         ID_TYPE NOT NULL,
   SALE_FLAG             FLAG_TYPE,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
