
CREATE TABLE LOGIN_TRACKING
(
   LOGIN_TRACKING_ID    ID_TYPE NOT NULL,
   LOGIN_DATE           DATE_TYPE NOT NULL,
   USER_ID              ID_TYPE NOT NULL,
   USER_NAME            USERNAME_TYPE NOT NULL,
   IP_ADDRESS           IP_TYPE,
   LOGOUT_DATE          DATE_TYPE,
   CREATE_DATE          DATE_TYPE NOT NULL,
   CREATE_BY            ID_TYPE NOT NULL,
   MODIFY_DATE          DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
