
CREATE TABLE MARITAL_STATUS
(
   MARITAL_ID            ID_TYPE NOT NULL,
   MARITAL_NAME          CODE_TYPE NOT NULL,
   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
