
CREATE TABLE PART_TYPE
(
   PART_TYPE_ID          ID_TYPE NOT NULL,
   PART_TYPE_NO          CODE_TYPE NOT NULL UNIQUE,
   PART_TYPE_NAME        CODE_TYPE NOT NULL UNIQUE,
   RAW_FLAG              FLAG_TYPE,
   PART_GROUP_ID         ID_TYPE,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
