
CREATE TABLE PART_GROUP
(
   PART_GROUP_ID         ID_TYPE NOT NULL,
   PART_GROUP_NO         CODE_TYPE NOT NULL UNIQUE,
   PART_GROUP_NAME       CODE_TYPE NOT NULL UNIQUE,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
