CREATE TABLE PRODUCT_STATUS
(
   PRODUCT_STATUS_ID     ID_TYPE NOT NULL,
   PRODUCT_STATUS_NO     CODE_TYPE NOT NULL UNIQUE,
   PRODUCT_STATUS_NAME   CODE_TYPE NOT NULL UNIQUE,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
