CREATE TABLE PRODUCT_TYPE
(
   PRODUCT_TYPE_ID       ID_TYPE NOT NULL,
   PRODUCT_TYPE_NO       CODE_TYPE NOT NULL UNIQUE,
   PRODUCT_TYPE_NAME     CODE_TYPE NOT NULL UNIQUE,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
