
CREATE TABLE RC_RATE
(
   RC_RATE_ID            ID_TYPE NOT NULL,
   SOC_FEATURE_ID        ID_TYPE NOT NULL,
   RATE_AMOUNT           MONEY_TYPE NOT NULL,
   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
