
CREATE TABLE REASON
(
   REASON_ID             ID_TYPE NOT NULL,
   REASON_NO             CODE_TYPE NOT NULL,
   REASON_NAME           CODE_TYPE NOT NULL,
   AREA                  ID_TYPE,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
