
CREATE TABLE RESOURCE
(
   RESOURCE_ID           ID_TYPE NOT NULL,
   RESOURCE_NO           CODE_TYPE NOT NULL,
   RESOURCE_NAME         NAME_TYPE NOT NULL,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
