
CREATE TABLE RECEIPT_ITEM
(
   RECEIPT_ITEM_ID       ID_TYPE NOT NULL,
   BILLING_DOC_ID        ID_TYPE NOT NULL,
   DO_ID                 ID_TYPE NOT NULL,
   RECEIPT_ITEM_AMOUNT   MONEY_TYPE,
   DISCOUNT_AMOUNT       MONEY_TYPE,
   DEPOSIT_AMOUNT        MONEY_TYPE,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
