
CREATE TABLE RIGHT_ITEM
(
   RIGHT_ID             ID_TYPE NOT NULL,
   RIGHT_ITEM_DESC      DESC_TYPE,
   DEFAULT_VALUE        FLAG_TYPE NOT NULL,
   RIGHT_ITEM_NAME      NAME_TYPE NOT NULL,
   PARENT_ID            ID_TYPE,

   CREATE_DATE          DATE_TYPE NOT NULL,
   CREATE_BY            ID_TYPE NOT NULL,
   MODIFY_DATE          DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
