CREATE TABLE SGROUP_ITEM
(
   SGROUP_ITEM_ID        ID_TYPE NOT NULL,
   STATUS_GROUP_ID       ID_TYPE NOT NULL,
   STATUS_ID             ID_TYPE NOT NULL,
   SELECT_FLAG           FLAG_TYPE,
   GUI_ID                ID_TYPE,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
