
CREATE TABLE SOC_FEATURE
(
   SOC_FEATURE_ID        ID_TYPE NOT NULL,
   SOC_ID                ID_TYPE NOT NULL,
   FEATURE_ID            ID_TYPE,
   PART_ITEM_ID          ID_TYPE,
   RC_FLAG               FLAG_TYPE NOT NULL,
   UC_FLAG               FLAG_TYPE NOT NULL,
   OC_FLAG               FLAG_TYPE NOT NULL,
   AC_FLAG               FLAG_TYPE NOT NULL,
   RATE_TYPE             ID_TYPE NOT NULL,
   MINIMUM_FLAG          FLAG_TYPE NOT NULL,
   MINIMUM_UNIT          MONEY_TYPE NOT NULL,
   USE_START_FLAG        FLAG_TYPE NOT NULL,
   USE_END_FLAG          FLAG_TYPE NOT NULL,
   ROUNDING_FACTOR       MONEY_TYPE NOT NULL,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
