
CREATE TABLE SUPPLIER_NAME
(
   SUPPLIER_NAME_ID      ID_TYPE NOT NULL,
   SUPPLIER_ID           ID_TYPE NOT NULL,
   NAME_ID               ID_TYPE NOT NULL,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
