CREATE TABLE SUPPLIER_GRADE
(
   SUPPLIER_GRADE_ID     ID_TYPE NOT NULL,
   SUPPLIER_GRADE_NO     CODE_TYPE NOT NULL,
   SUPPLIER_GRADE_NAME   CODE_TYPE NOT NULL,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
