
CREATE TABLE SUPPLIER_ADDRESS
(
   SUPPLIER_ADDRESS_ID   ID_TYPE NOT NULL,
   SUPPLIER_ID           ID_TYPE NOT NULL,
   ADDRESS_ID            ID_TYPE NOT NULL,
   ADDRESS_TYPE          ID_TYPE,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
