
CREATE TABLE USER_ACCOUNT
(
   USER_ID              ID_TYPE NOT NULL,
   USER_NAME            USERNAME_TYPE NOT NULL,
   USER_PASSWORD        PASSWORD_TYPE NOT NULL,
   USER_DESC            DESC_TYPE,
   USER_STATUS          FLAG_TYPE,
   GROUP_ID             ID_TYPE NOT NULL,
   CHECK_EXPIRE         FLAG_TYPE NOT NULL,
   EXPIRE_DATE          DATE_TYPE,
   FROM_TIME            TIME_TYPE,
   TO_TIME              TIME_TYPE,
   EXCEPTION_FLAG        FLAG_TYPE,

   CREATE_DATE          DATE_TYPE NOT NULL,
   CREATE_BY            ID_TYPE NOT NULL,
   MODIFY_DATE          DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
