
CREATE TABLE USER_GROUP
(
   GROUP_ID             ID_TYPE NOT NULL,
   GROUP_NAME           GROUPNAME_TYPE NOT NULL,
   GROUP_DESC           DESC_TYPE,
   MAX_USER             LEN_TYPE,
   GROUP_STATUS         FLAG_TYPE,
   CREATE_DATE          DATE_TYPE NOT NULL,
   CREATE_BY            ID_TYPE NOT NULL,
   MODIFY_DATE          DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
