
ALTER TABLE AGREEMENT ADD CONSTRAINT AGREEMENT_ID_PK PRIMARY KEY (AGREEMENT_ID);
ALTER TABLE AGREEMENT ADD CONSTRAINT AGR_SOC_FEATURE_ID_FK FOREIGN KEY (SOC_FEATURE_ID) REFERENCES SOC_FEATURE;
ALTER TABLE AGREEMENT ADD CONSTRAINT AGR_SOC_ID_FK FOREIGN KEY (SOC_ID) REFERENCES SOC;
ALTER TABLE AGREEMENT ADD CONSTRAINT AGR_SUBSCRIBER_ID_FK FOREIGN KEY (SUBSCRIBER_ID) REFERENCES SUBSCRIBER;
