ALTER TABLE BILLING_ADJUST ADD CONSTRAINT BILLING_ADJUST_ID_PK PRIMARY KEY (BILLING_ADJUST_ID);
ALTER TABLE BILLING_ADJUST ADD CONSTRAINT BILLING_ADJUST_BDOC_ID FOREIGN KEY (BILLING_DOC_ID) REFERENCES BILLING_DOC;
ALTER TABLE BILLING_ADJUST ADD CONSTRAINT BILLING_ADJUST_IDOC_ID FOREIGN KEY (INVENTORY_DOC_ID) REFERENCES INVENTORY_DOC;