ALTER TABLE BILLING_DOC ADD CONSTRAINT BILLING_DOC_ID_PK PRIMARY KEY (BILLING_DOC_ID);
ALTER TABLE BILLING_DOC ADD CONSTRAINT BILLING_DOC_BILLING_ADDR_ID_FK FOREIGN KEY (BILLING_ADDRESS_ID) REFERENCES ADDRESS;
ALTER TABLE BILLING_DOC ADD CONSTRAINT BILLING_DOC_ENP_ADDR_ID_FK FOREIGN KEY (ENTERPRISE_ADDRESS_ID) REFERENCES ADDRESS;
ALTER TABLE BILLING_DOC ADD CONSTRAINT BILLING_DOC_ENTERPRISE_ID_FK FOREIGN KEY (ENTERPRISE_ID) REFERENCES ENTERPRISE;
ALTER TABLE BILLING_DOC ADD CONSTRAINT BILLING_DOC_ACCEPT_BY_FK FOREIGN KEY (ACCEPT_BY) REFERENCES EMPLOYEE;
ALTER TABLE BILLING_DOC ADD CONSTRAINT BILLING_DOC_RECEIVE_BY_FK FOREIGN KEY (RECEIVE_BY) REFERENCES EMPLOYEE;
ALTER TABLE BILLING_DOC ADD CONSTRAINT BILLING_DOC_INV_DOC_ID_FK FOREIGN KEY (INVENTORY_DOC_ID) REFERENCES INVENTORY_DOC;
ALTER TABLE BILLING_DOC ADD CONSTRAINT BILLING_DOC_SUPPLIER_ID_FK FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER;
ALTER TABLE BILLING_DOC ADD CONSTRAINT BILLING_DOC_RESOURCE_ID_FK FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCE;