
ALTER TABLE CUSTOMER_ADDRESS ADD CONSTRAINT CUSTOMER_ADDRESS_ID_PK PRIMARY KEY (CUSTOMER_ADDRESS_ID);
ALTER TABLE CUSTOMER_ADDRESS ADD CONSTRAINT CUSTOMER_ADDR_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER;
ALTER TABLE CUSTOMER_ADDRESS ADD CONSTRAINT CUSTOMER_ADDRESS_ID_FK FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS;
ALTER TABLE CUSTOMER_ADDRESS ADD CONSTRAINT CUSTOMER_ADDRESS_TYPE_FK FOREIGN KEY (ADDRESS_TYPE) REFERENCES ADDRESS_TYPE;
