
ALTER TABLE CUSTOMER_NAME ADD CONSTRAINT CUSTOMER_NAME_ID_PK PRIMARY KEY (CUSTOMER_NAME_ID);
ALTER TABLE CUSTOMER_NAME ADD CONSTRAINT CUSTOMER_NAME_CST_ID_FK2 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER;
ALTER TABLE CUSTOMER_NAME ADD CONSTRAINT CUSTOMER_NAME_ID_FK3 FOREIGN KEY (NAME_ID) REFERENCES NAME;
