ALTER TABLE DO_ITEM ADD CONSTRAINT DO_ITEM_ID_PK PRIMARY KEY (DO_ITEM_ID);
ALTER TABLE DO_ITEM ADD CONSTRAINT DO_ITEM_DO_ID_FK FOREIGN KEY (DO_ID) REFERENCES BILLING_DOC;
ALTER TABLE DO_ITEM ADD CONSTRAINT DO_ITEM_PIG_STATUS_ID_FK FOREIGN KEY (PIG_STATUS) REFERENCES PRODUCT_STATUS;
