
ALTER TABLE EMP_POSITION ADD CONSTRAINT POSITION_ID_PK PRIMARY KEY (POSITION_ID);
ALTER TABLE EMP_POSITION ADD CONSTRAINT PPOSITION_ID_FK FOREIGN KEY (POSITION_ID) REFERENCES EMP_POSITION(POSITION_ID);
