
ALTER TABLE ENTERPRISE_NAME ADD CONSTRAINT ENTERPRISE_NAME_ID_PK PRIMARY KEY (ENTERPRISE_NAME_ID);
ALTER TABLE ENTERPRISE_NAME ADD CONSTRAINT ENTERPRISE_ENP_ID_FK2 FOREIGN KEY (ENTERPRISE_ID) REFERENCES ENTERPRISE;
ALTER TABLE ENTERPRISE_NAME ADD CONSTRAINT ENTERPRISE_NAME_ID_FK3 FOREIGN KEY (NAME_ID) REFERENCES NAME;
