
ALTER TABLE ENTERPRISE_ADDRESS ADD CONSTRAINT ENTERPRISE_ADDR_ID_PK PRIMARY KEY (ENTERPRISE_ADDRESS_ID);
ALTER TABLE ENTERPRISE_ADDRESS ADD CONSTRAINT ENTERPRISE_ENP_ID_FK FOREIGN KEY (ENTERPRISE_ID) REFERENCES ENTERPRISE;
