
ALTER TABLE EXPORT_ITEM ADD CONSTRAINT EXPORT_ITEM_ID_PK PRIMARY KEY (EXPORT_ITEM_ID);
ALTER TABLE EXPORT_ITEM ADD CONSTRAINT EXPORT_ITEM_DOC_ID_FK FOREIGN KEY (INVENTORY_DOC_ID) REFERENCES INVENTORY_DOC;
ALTER TABLE EXPORT_ITEM ADD CONSTRAINT EXPORT_ITEM_PART_ID_FK FOREIGN KEY (PART_ITEM_ID) REFERENCES PART_ITEM;
ALTER TABLE EXPORT_ITEM ADD CONSTRAINT EXPORT_ITEM_LOCATION_ID_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION;
ALTER TABLE EXPORT_ITEM ADD CONSTRAINT EXPORT_ITEM_HOUSE_ID_FK FOREIGN KEY (HOUSE_ID) REFERENCES LOCATION;
ALTER TABLE EXPORT_ITEM ADD CONSTRAINT EXPORT_ITEM_PIG_ID_FK FOREIGN KEY (PIG_ID) REFERENCES PART_ITEM;
