
ALTER TABLE FORMULA_ITEM ADD CONSTRAINT FORMULA_ITEM_ID_PK PRIMARY KEY (FORMULA_ITEM_ID);
ALTER TABLE FORMULA_ITEM ADD CONSTRAINT FORMULA_ITEM_FORMULA_ID_FK FOREIGN KEY (FORMULA_ID) REFERENCES FORMULA;
ALTER TABLE FORMULA_ITEM ADD CONSTRAINT FORMULA_ITEM_COMPONENT_ID_FK FOREIGN KEY (COMPONENT_ID) REFERENCES FORMULA;
ALTER TABLE FORMULA_ITEM ADD CONSTRAINT FORMULA_ITEM_PART_ID_FK FOREIGN KEY (PART_ITEM_ID) REFERENCES PART_ITEM;
