ALTER TABLE HGROUP_ITEM ADD CONSTRAINT HGROUP_ITEM_ID_PK PRIMARY KEY (HGROUP_ITEM_ID);
ALTER TABLE HGROUP_ITEM ADD CONSTRAINT HGROUP_ITEM_HGROUP_ID_FK FOREIGN KEY (HOUSE_GROUP_ID) REFERENCES HOUSE_GROUP;
ALTER TABLE HGROUP_ITEM ADD CONSTRAINT HGROUP_ITEM_LOC_ID_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION;
