
ALTER TABLE IMPORT_ITEM ADD CONSTRAINT IMPORT_ITEM_ID_PK PRIMARY KEY (IMPORT_ITEM_ID);
ALTER TABLE IMPORT_ITEM ADD CONSTRAINT IMPORT_ITEM_DOC_ID_FK FOREIGN KEY (INVENTORY_DOC_ID) REFERENCES INVENTORY_DOC;
ALTER TABLE IMPORT_ITEM ADD CONSTRAINT IMPORT_ITEM_PART_ID_FK FOREIGN KEY (PART_ITEM_ID) REFERENCES PART_ITEM;
ALTER TABLE IMPORT_ITEM ADD CONSTRAINT IMPORT_ITEM_LOCATION_ID_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION;
