
ALTER TABLE INVENTORY_DOC ADD CONSTRAINT INVENTORY_DOC_ID_PK PRIMARY KEY (INVENTORY_DOC_ID);
ALTER TABLE INVENTORY_DOC ADD CONSTRAINT INVENTORY_DOC_SUPPLIER_ID_FK1 FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER;
ALTER TABLE INVENTORY_DOC ADD CONSTRAINT INVENTORY_DOC_SUPPLIER_ID_FK2 FOREIGN KEY (DELIVERY_ID) REFERENCES SUPPLIER;
ALTER TABLE INVENTORY_DOC ADD CONSTRAINT INVENTORY_DOC_EMP_ID_FK2 FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE;
ALTER TABLE INVENTORY_DOC ADD CONSTRAINT INVENTORY_REASON_ID_FK FOREIGN KEY (REASON_ID) REFERENCES REASON;
