
ALTER TABLE LOT_ITEM ADD CONSTRAINT LOT_ITEM_ID_PK PRIMARY KEY (LOT_ITEM_ID);
ALTER TABLE LOT_ITEM ADD CONSTRAINT LOT_ITEM_DOC_ID_FK FOREIGN KEY (INVENTORY_DOC_ID) REFERENCES INVENTORY_DOC;
ALTER TABLE LOT_ITEM ADD CONSTRAINT LOT_ITEM_PART_ID_FK FOREIGN KEY (PART_ITEM_ID) REFERENCES PART_ITEM;
ALTER TABLE LOT_ITEM ADD CONSTRAINT LOT_ITEM_LOCATION_ID_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION;
ALTER TABLE LOT_ITEM ADD CONSTRAINT LOT_ITEM_REF_ID_FK FOREIGN KEY (LOT_REF_ID) REFERENCES LOT_ITEM;
ALTER TABLE LOT_ITEM ADD CONSTRAINT LOT_ITEM_LAYOUT_ID_FK FOREIGN KEY (LAYOUT_ID) REFERENCES LAY_OUT;
