
ALTER TABLE PART_ITEM ADD CONSTRAINT PART_ITEM_ID_PK PRIMARY KEY (PART_ITEM_ID);
ALTER TABLE PART_ITEM ADD CONSTRAINT PART_ITEM_UNIT_COUNT_FK FOREIGN KEY (UNIT_COUNT) REFERENCES UNIT;
ALTER TABLE PART_ITEM ADD CONSTRAINT PART_ITEM_PART_TYPE_FK FOREIGN KEY (PART_TYPE) REFERENCES PART_TYPE;
