ALTER TABLE PART_LOCATION ADD CONSTRAINT PART_LOCATION_ID_PK PRIMARY KEY (PART_LOCATION_ID);
ALTER TABLE PART_LOCATION ADD CONSTRAINT PART_LOCATION_PART_FK FOREIGN KEY (PART_ITEM_ID) REFERENCES PART_ITEM;
ALTER TABLE PART_LOCATION ADD CONSTRAINT PART_LOCATION_LOCATION_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION;
