
ALTER TABLE RECEIPT_ITEM ADD CONSTRAINT RECEIPT_ITEM_ID_PK PRIMARY KEY (RECEIPT_ITEM_ID);
ALTER TABLE RECEIPT_ITEM ADD CONSTRAINT RECEIPT_ITEM_DOC_ID_FK FOREIGN KEY (BILLING_DOC_ID) REFERENCES BILLING_DOC;
ALTER TABLE RECEIPT_ITEM ADD CONSTRAINT RECEIPT_ITEM_DO_ID_FK FOREIGN KEY (DO_ID) REFERENCES BILLING_DOC;
