ALTER TABLE SGROUP_ITEM ADD CONSTRAINT SGROUP_ITEM_ID_PK PRIMARY KEY (SGROUP_ITEM_ID);
ALTER TABLE SGROUP_ITEM ADD CONSTRAINT SGROUP_ITEM_SGROUP_ID_FK FOREIGN KEY (STATUS_GROUP_ID) REFERENCES STATUS_GROUP;
ALTER TABLE SGROUP_ITEM ADD CONSTRAINT SGROUP_ITEM_STATUS_ID_FK FOREIGN KEY (STATUS_ID) REFERENCES PRODUCT_STATUS;
