
ALTER TABLE SOC_FEATURE ADD CONSTRAINT SOC_FEATURE_ID_PK PRIMARY KEY (SOC_FEATURE_ID);
ALTER TABLE SOC_FEATURE ADD CONSTRAINT SOC_SOC_ID_FK FOREIGN KEY (SOC_ID) REFERENCES SOC;
ALTER TABLE SOC_FEATURE ADD CONSTRAINT SOC_FEATURE_ID_FK FOREIGN KEY (FEATURE_ID) REFERENCES FEATURE;
ALTER TABLE SOC_FEATURE ADD CONSTRAINT SOC_PART_ITEM_ID_FK FOREIGN KEY (PART_ITEM_ID) REFERENCES PART_ITEM;
