
ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_DATA_PK PRIMARY KEY (SUPPLIER_ID);
ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_DATA_GRADE_FK FOREIGN KEY (SUPPLIER_GRADE) REFERENCES SUPPLIER_GRADE;
ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_DATA_STATUS_FK FOREIGN KEY (SUPPLIER_STATUS) REFERENCES SUPPLIER_STATUS;
ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_DATA_TYPE_FK FOREIGN KEY (SUPPLIER_TYPE) REFERENCES SUPPLIER_TYPE;
