
ALTER TABLE SUBLOT_ITEM ADD CONSTRAINT SUBLOT_ITEM_ID_PK PRIMARY KEY (SUBLOT_ITEM_ID);
ALTER TABLE SUBLOT_ITEM ADD CONSTRAINT SUBLOT_LOT_ITEM_ID_FK1 FOREIGN KEY (LOT_ITEM_ID) REFERENCES LOT_ITEM;
ALTER TABLE SUBLOT_ITEM ADD CONSTRAINT SUBLOT_FROM_LOT_FK2 FOREIGN KEY (FROM_LOT_ID) REFERENCES LOT_ITEM;
