
ALTER TABLE SUPPLIER_NAME ADD CONSTRAINT SUPPLIER_NAME_ID_PK PRIMARY KEY (SUPPLIER_NAME_ID);
ALTER TABLE SUPPLIER_NAME ADD CONSTRAINT SUPPLIER_NAME_CST_ID_FK2 FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER;
ALTER TABLE SUPPLIER_NAME ADD CONSTRAINT SUPPLIER_NAME_ID_FK3 FOREIGN KEY (NAME_ID) REFERENCES NAME;
