
ALTER TABLE SUPPLIER_CONTACT ADD CONSTRAINT SUPPLIER_CONTACT_ID_PK PRIMARY KEY (SUPPLIER_CONTACT_ID);
ALTER TABLE SUPPLIER_CONTACT ADD CONSTRAINT SUPPLIER_CONTACT_CST_ID_FK2 FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER;
ALTER TABLE SUPPLIER_CONTACT ADD CONSTRAINT SUPPLIER_CONTACT_NAME_ID_FK2 FOREIGN KEY (NAME_ID) REFERENCES NAME;
