ALTER TABLE YEAR_WEEK ADD CONSTRAINT YEAR_WEEK_ID_PK PRIMARY KEY (YEAR_WEEK_ID);
ALTER TABLE YEAR_WEEK ADD CONSTRAINT YEAR_WEEK_YEAR_ID_FK1 FOREIGN KEY (YEAR_SEQ_ID) REFERENCES YEAR_SEQ;
ALTER TABLE YEAR_WEEK ADD CONSTRAINT YEAR_WEEK_PART_ID_FK1 FOREIGN KEY (PART_ITEM_ID1) REFERENCES PART_ITEM;
ALTER TABLE YEAR_WEEK ADD CONSTRAINT YEAR_WEEK_PART_ID_FK2 FOREIGN KEY (PART_ITEM_ID2) REFERENCES PART_ITEM;
ALTER TABLE YEAR_WEEK ADD CONSTRAINT YEAR_WEEK_PART_ID_FK3 FOREIGN KEY (PART_ITEM_ID3) REFERENCES PART_ITEM;

