CREATE DOMAIN ACTION_TYPE AS CHAR(1) CHECK(VALUE IN ('I', 'D', 'U'));
CREATE DOMAIN ADDRESS_TYPE AS VARCHAR(100);
CREATE DOMAIN AMOUNT_TYPE AS NUMERIC(9, 2);
CREATE DOMAIN AMPHUR_TYPE AS VARCHAR (75);
CREATE DOMAIN BNKACC_TYPE  AS VARCHAR (75);
CREATE DOMAIN BNKBRN_TYPE AS VARCHAR (75);
CREATE DOMAIN BNKNM_TYPE  AS VARCHAR (75);
CREATE DOMAIN CHARGE_TYPE  AS INTEGER;
CREATE DOMAIN CHG_TYPE AS VARCHAR (5);
CREATE DOMAIN CODE_TYPE AS VARCHAR(20);
CREATE DOMAIN COLOR_TYPE AS INTEGER;
CREATE DOMAIN COUNTRY_TYPE AS VARCHAR (100);
CREATE DOMAIN CREDIT_TYPE AS INTEGER;
CREATE DOMAIN CTL_TYPE AS CHAR(2);
CREATE DOMAIN CUT_TYPE AS CHAR(2);
CREATE DOMAIN CYCLE_NO_TYPE AS INTEGER;
CREATE DOMAIN DATA_TYPE AS INTEGER;
CREATE DOMAIN DATE_TYPE AS VARCHAR(19);
CREATE DOMAIN DAY_TYPE AS INTEGER;
CREATE DOMAIN DBCR_TYPE AS CHAR(1) CHECK(VALUE IN ('D', 'C'));
CREATE DOMAIN DESC_TYPE AS VARCHAR(300);
CREATE DOMAIN DISTRICT_TYPE AS VARCHAR (75);
CREATE DOMAIN EMAIL_TYPE AS VARCHAR(30);
CREATE DOMAIN FAX_TYPE AS VARCHAR(30);
CREATE DOMAIN FLAG_TYPE AS CHAR(1) CHECK(VALUE IN ('Y', 'N'));
CREATE DOMAIN GROUPNAME_TYPE AS VARCHAR(50);
CREATE DOMAIN HEIGHT_TYPE AS NUMERIC(9, 2);
CREATE DOMAIN HOME_TYPE AS VARCHAR (70);
CREATE DOMAIN ID_TYPE  AS INTEGER;
CREATE DOMAIN IP_TYPE AS VARCHAR(50);

CREATE TABLE JOB_PLAN
(
   JOB_PLAN_ID           ID_TYPE NOT NULL,
   ACCOUNT_ID            ID_TYPE NOT NULL,
   JOB_DATE              DATE_TYPE NOT NULL,
   REQUEST_BY            ID_TYPE,
   REQUEST_DATE          DATE_TYPE,
   JOB_DESC              DESC_TYPE,
   POST_STATUS           FLAG_TYPE,
   FINISH_DATE           DATE_TYPE,
   LOT_IMPORT_ID         ID_TYPE,
   LOT_EXPORT_ID         ID_TYPE,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);CREATE DOMAIN KEY_TYPE AS VARCHAR(10);
CREATE DOMAIN LEN_TYPE AS NUMERIC(3, 0);
CREATE DOMAIN LNAME_TYPE AS VARCHAR (75);
CREATE DOMAIN MESSAGE_TYPE AS CHAR(1);
CREATE DOMAIN MONEY_TYPE AS NUMERIC(13,2);
CREATE DOMAIN MONTH_TYPE AS INTEGER;
CREATE DOMAIN MOO_TYPE AS VARCHAR (10);
CREATE DOMAIN NAME_TYPE AS VARCHAR(30);
CREATE DOMAIN PASSWORD_TYPE AS VARCHAR(50);
CREATE DOMAIN PERCENT_TYPE AS NUMERIC(2, 0);
CREATE DOMAIN PHONE_TYPE AS VARCHAR(30);
CREATE DOMAIN PICSIZE_TYPE NUMERIC (5, 0);
CREATE DOMAIN PROVINCE_TYPE  AS VARCHAR (75);
CREATE DOMAIN QUOATA_TYPE AS CHAR(1) CHECK(VALUE IN ('M', 'F'));
CREATE DOMAIN REFCOUNT_TYPE AS INTEGER;
CREATE DOMAIN REGION_TYPE AS CHAR(2) CHECK(VALUE IN ('N', 'E', 'W', 'S', 'NE', 'M'));
CREATE DOMAIN RIGHT_TYPE AS VARCHAR(100);
CREATE DOMAIN RIGHTNAME_TYPE AS VARCHAR(50);
CREATE DOMAIN ROAD_TYPE AS VARCHAR (75);
CREATE DOMAIN SNAME_TYPE AS VARCHAR (30);
CREATE DOMAIN SOI_TYPE AS VARCHAR (50);
CREATE DOMAIN STRING_TYPE AS VARCHAR(1024);
CREATE DOMAIN TAXID_TYPE AS VARCHAR(20);
CREATE DOMAIN TEXT_TYPE AS INTEGER;
CREATE DOMAIN TIME_TYPE AS VARCHAR(20);
CREATE DOMAIN UOM_TYPE  AS INTEGER;
CREATE DOMAIN USERNAME_TYPE AS VARCHAR(30);
CREATE DOMAIN VAR_TYPE AS CHAR(2) CHECK(VALUE IN ('I', 'L', 'F', 'DT', 'S', 'B'));
CREATE DOMAIN VILLAGE_TYPE AS VARCHAR (75);
CREATE DOMAIN WEB_TYPE AS VARCHAR(30);
CREATE DOMAIN WEIGHT_TYPE AS NUMERIC(9, 2);
CREATE DOMAIN YEAR_TYPE AS INTEGER;
CREATE DOMAIN ZIP_TYPE AS VARCHAR(30);
