VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "CRight"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public GROUP_ID As Long
Public RIGHT_ID As Long
Public RIGHT_STATUS As String
Public RIGHT_ITEM_DESC As String
Public RIGHT_GROUP_ID As Long
Public DEFAULT_VALUE As String
Public RIGHT_ITEM_NAME As String

Public Flag As String
Public RightFlag As Long
